#!/usr/bin/env bash

GEOM='1631x23+289+0'
FONT='monospace:size=12'
LBAR=( lemonbar -d -g "$GEOM" -f "$FONT" -B '#222222' -o 1 -u 2 )

notify() { (echo "%{F$1}%{B$2} $3 %{B-}"; sleep 1) | "${LBAR[@]}" & }

show() {
    volume=$(pactl get-sink-volume 0 | awk 'NR==1 { print $5 }')
    mute=$(pactl get-sink-mute 0 | awk '{ print $2 }')
    case "$mute" in
        'no') notify '#a9b665' '#34381b' "$volume" ;;
        'yes') notify '#ea6962' '#4c3432' "$volume" ;;
    esac
}

case "$@" in
    'dec_volume') pactl set-sink-volume 0 -5% && show ;;
    'inc_volume') pactl set-sink-volume 0 +5% && show ;;
    'toggle_mute') pactl set-sink-mute 0 toggle && show ;;
    'show') show ;;
    *) exit 0 ;;
esac

# amixer set Master 5%-
# amixer set Master 5%+
# amixer -D pulse set Master 1+ toggle

# vim: set ts=4 sw=4
