#!/usr/bin/env bash

hc() { herbstclient "$@" ;}

cmd=( chain . lock
            . use_index 0
            . load '(clients max:0)'
            . foreach --unique C clients. sprintf W "%{%c.winid}" C bring W
            . unlock )

hc "${cmd[@]}"

# vim: set ts=4 sw=4
